apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: example-tls
  namespace: default
spec:
  secretName: sec-example
  duration: 2160h        # 90 days
  renewBefore: 720h      # auto-renew 30 days before expiry
  issuerRef:
    name: selfsigned-issuer
    kind: Issuer
  dnsNames:
  - example.com