apiVersion: v1
kind: Pod
metadata:
  name: hello-apparmor-new
spec:
  containers:
  - name: hello
    image: busybox:1.28
    command: ["sh", "-c", "sleep 1h"]
    securityContext:
      appArmorProfile:
        type: Localhost
        localhostProfile: k8s-apparmor-example-deny-write